### ISSUE TITLE
icalendar 2.5.0: ArgumentError when calling calendar.parse

### ISSUE THREAD

**Issue by hdost** [icalendar/icalendar#194]
Passes in 2.4.1

Failure in 2.5.0
```
     NoMethodError:
       undefined method `present?' for nil:NilClass
     # /home/h.dost/.gem/ruby/gems/icalendar-2.5.0/lib/icalendar/values/time_with_zone.rb:22:in `initialize'
     # /home/h.dost/.gem/ruby/gems/icalendar-2.5.0/lib/icalendar/values/date_time.rb:22:in `initialize'
     # /home/h.dost/.gem/ruby/gems/icalendar-2.5.0/lib/icalendar/parser.rb:66:in `new'
     # /home/h.dost/.gem/ruby/gems/icalendar-2.5.0/lib/icalendar/parser.rb:66:in `wrap_property_value'
     # /home/h.dost/.gem/ruby/gems/icalendar-2.5.0/lib/icalendar/parser.rb:38:in `parse_property'
     # /home/h.dost/.gem/ruby/gems/icalendar-2.5.0/lib/icalendar/parser.rb:118:in `parse_component'
     # /home/h.dost/.gem/ruby/gems/icalendar-2.5.0/lib/icalendar/parser.rb:113:in `parse_component'
     # /home/h.dost/.gem/ruby/gems/icalendar-2.5.0/lib/icalendar/parser.rb:111:in `parse_component'
     # /home/h.dost/.gem/ruby/gems/icalendar-2.5.0/lib/icalendar/parser.rb:28:in `parse'
     # /home/h.dost/.gem/ruby/gems/icalendar-2.5.0/lib/icalendar/component.rb:16:in `parse'
     # ./spec/unit/events_spec.rb:28:in `block (3 levels) in <top (required)>'
```

**Comment by jewilmeer** [comment]
This is because Active support is now required to handle times with timezones. I think the 2.5.0 upgrade should be a major upgrade, as it obviously has breaking changes.

See https://github.com/icalendar/icalendar/blob/c554f8dd258ad7c90fb6ff738e22c09b4f4f457b/icalendar.gemspec#L19
