### ISSUE TITLE
SyntaxError for icalendar-1.5.0

### ISSUE THREAD

**Issue by woodyhuang** [icalendar/icalendar#48]
I am using backlog-1.0.6 as a plugin of redmine-2.2.4, so it refs icalendar-1.5.0.

`bundle install` worked well, while `rake` failed with a SyntaxError ?

I am using ruby-1.8.7 and gem-1.8.15.

Error msg looks like below:

```
component.rb:206:in `generate_multi_setter': compile error (SyntaxError)
component.rb:201: undefined (?...) sequence: /^[^"].*(?<!\\),.*[^"]$/
component.rb:202: undefined (?...) sequence: /(?<!\\),/
        from /var/lib/gems/1.8/gems/icalendar-1.5.0/lib/icalendar/component.rb:244:in `ical_multi_property'
        from /var/lib/gems/1.8/gems/icalendar-1.5.0/lib/icalendar/component/event.rb:80
        from /var/lib/gems/1.8/gems/icalendar-1.5.0/lib/icalendar.rb:28:in `require'
        from /var/lib/gems/1.8/gems/icalendar-1.5.0/lib/icalendar.rb:28
        from /var/lib/gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
        from /var/lib/gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
        from /var/lib/gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
        from /var/lib/gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `require'
        from /var/lib/gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
        from /var/lib/gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
        from /var/lib/gems/1.8/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
        from /data/redmine/config/application.rb:7
        from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from /data/redmine/config/environment.rb:2
        from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from config.ru:4
        from /var/lib/gems/1.8/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
        from /var/lib/gems/1.8/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1
```

**Comment by palladius** [comment]
I have the same problem - I wish I could use ruby1.9 or 2.0 -> it'll break my old app :-(

I'm using icalendar-1.5.2 - I'll try 1.4.3 and see if it works.

**Comment by palladius** [comment]
Yup - v.1.4.3 works like a charm. Thanks eveyrone!
